// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcAS13pXmsaiWoqAc08o69ojKDyl3oyGw',
    appId: '1:585899141002:web:545d7e1721a44bff264a73',
    messagingSenderId: '585899141002',
    projectId: 'study-side-d555e',
    authDomain: 'study-side-d555e.firebaseapp.com',
    storageBucket: 'study-side-d555e.firebasestorage.app',
    measurementId: 'G-QF6T9BDPDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbeAh7rdVUlRVL0zJQmYHqiQt-Sn1sz_0',
    appId: '1:585899141002:android:6bd9645a6c907319264a73',
    messagingSenderId: '585899141002',
    projectId: 'study-side-d555e',
    storageBucket: 'study-side-d555e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGruapsWktXhe8cI9PNmP8CL84vUT7CIs',
    appId: '1:585899141002:ios:2bd8c040c3cf6221264a73',
    messagingSenderId: '585899141002',
    projectId: 'study-side-d555e',
    storageBucket: 'study-side-d555e.firebasestorage.app',
    iosBundleId: 'com.example.studySide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGruapsWktXhe8cI9PNmP8CL84vUT7CIs',
    appId: '1:585899141002:ios:2bd8c040c3cf6221264a73',
    messagingSenderId: '585899141002',
    projectId: 'study-side-d555e',
    storageBucket: 'study-side-d555e.firebasestorage.app',
    iosBundleId: 'com.example.studySide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcAS13pXmsaiWoqAc08o69ojKDyl3oyGw',
    appId: '1:585899141002:web:413ddfe3638906ef264a73',
    messagingSenderId: '585899141002',
    projectId: 'study-side-d555e',
    authDomain: 'study-side-d555e.firebaseapp.com',
    storageBucket: 'study-side-d555e.firebasestorage.app',
    measurementId: 'G-CRVDWCF52S',
  );
}
